<table>
    <thead>
        <tr>
            <th>application_no</th>
            <th>year</th>
            <th>full_name</th>
            <th>full_name_sinhala</th>
            <th>full_name_tamil</th>
            <th>name_marking</th>
            <th>initials</th>
            <th>title</th>
            <th>gender</th>
            <th>id_type</th>
            <th>id_no</th>
            <th>dob</th>
            <th>email</th>
            <th>phone</th>
            <th>mobile</th>
            <th>address1</th>
            <th>address2</th>
            <th>address3</th>
            <th>district</th>
            <th>country</th>
            <th>citizenship</th>
            <th>nationality</th>
            <th>qualification_type</th>
            <th>qualification_pending</th>
            <th>need_different_req</th>
            <th>al_year</th>
            <th>al_index_no</th>
            <th>al_type</th>
            <th>al_subject1</th>
            <th>al_result1</th>
            <th>al_subject2</th>
            <th>al_result2</th>
            <th>al_subject3</th>
            <th>al_result3</th>
            <th>al_subject4</th>
            <th>al_result4</th>
            <th>ol_year1</th>
            <th>ol_subject1</th>
            <th>ol_result1</th>
            <th>ol_year2</th>
            <th>ol_subject2</th>
            <th>ol_result2</th>
            <th>type</th>
            <th>payment_category</th>
            <th>payment_type</th>
            <th>amount</th>
            <th>over_payment</th>
            <th>surcharge</th>
            <th>bank</th>
            <th>bank_branch</th>
            <th>paid_date</th>
            <th>invoice_no</th>
        </tr>
    </thead>
    <tbody>
        @foreach($data as $application)
        <tr>
            <td>{{$application->application_no}}</td>
            <td>{{$application->year}}</td>
            <td>{{$application->full_name}}</td>
            <td>{{$application->full_name_sinhala}}</td>
            <td>{{$application->full_name_tamil}}</td>
            <td>{{$application->name_marking}}</td>
            <td>{{$application->initials}}</td>
            <td>{{$application->title}}</td>
            <td>{{$application->gender}}</td>
            <td>{{$application->id_type}}</td>
            <td>{{$application->id_no}}</td>
            <td>{{$application->dob}}</td>
            <td>{{$application->email}}</td>
            <td>{{$application->phone}}</td>
            <td>{{$application->mobile}}</td>
            <td>{{$application->address1}}</td>
            <td>{{$application->address2}}</td>
            <td>{{$application->address3}}</td>
            <td>{{$application->district}}</td>
            <td>{{$application->country}}</td>
            <td>{{$application->citizenship}}</td>
            <td>{{$application->nationality}}</td>
            <td>{{$application->qualification_type}}</td>
            <td>{{$application->qualification_pending}}</td>
            <td>{{$application->need_different_req}}</td>
            @if($application->al)
                <td>{{$application->al->year}}</td>
                <td>{{$application->al->index_no}}</td>
                <td>{{$application->al->type}}</td>
                <td>{{$ALSubject[$application->al->subject1]}}</td>
                <td>{{$application->al->result1}}</td>
                <td>{{$ALSubject[$application->al->subject2]}}</td>
                <td>{{$application->al->result2}}</td>
                <td>{{$ALSubject[$application->al->subject3]}}</td>
                <td>{{$application->al->result3}}</td>
                <td>{{$ALSubject[$application->al->subject4]}}</td>
                <td>{{$application->al->result4}}</td>
            @else
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
                <td>-</td>
            @endif
            @foreach($application->ol as $olRow)
                <td>{{$olRow->year}}</td>
                <td>{{$olRow->subject}}</td>
                <td>{{$olRow->result}}</td>
            @endforeach

            <td>{{$application->payment->type}}</td>
            <td>{{$application->payment->payment_category}}</td>
            <td>{{$application->payment->payment_type}}</td>
            <td>{{$application->payment->amount}}</td>
            <td>{{$application->payment->over_payment}}</td>
            <td>{{$application->payment->surcharge}}</td>
            <td>{{$application->payment->bank}}</td>
            <td>{{$application->payment->bank_branch}}</td>
            <td>{{$application->payment->paid_date}}</td>
            <td>{{$application->payment->invoice_no}}</td>
        @endforeach
        </tr>
    </tbody>
</table>